### ISSUE TITLE
Becoming Belters: a project going Civboot's way

### ISSUE THREAD

**Issue by ghost** [civboot/civboot#10]
Yesterday I've discovered your project Civboot. While I'm yet to really deeply dig into it, I think I'm working on something you might find is "going your way".

I want to go to space with people so we could live as belters. And so that later on our progeny can move out into the galaxy and beyond.

The overlap with Civboot is obvious - my project amounts to creating a breakaway civilization - a civilization that can and does regenerate it's entire technology stack using only several thousand people, and this technology stack provides everything. And I mean EVERYTHING - even the air for breathing.

The critical concepts are recycling and understandable technology. The two biggest technological hurdles are IC manufacturing and organic chemistry. The biggest hurdle of all is finding people to go with.

I'm writing to you mostly to appear on your radar. So you could know others are thinking thoughts similar to yours.

So far, I'm trying to start a company for making robots that will both provide a breeding ground for further technologies, provide money for further steps on the ladder and perhaps be a point that people can come around.

In addition I started a blog to serve as a "finder" that will hopefully be discovered by people also looking to go to space.

The blog is at https://becomingbelte.rs/ As I and hopefully others discover and perfect our technology stack it should be published there. We might not publish things like breeder nuclear reactor designs because they are a WMD proliferation risk but in general all stuff whould eventually be published there.

You can also find some other of my stuff on https://github.com/akuktin/

The current plan is to launch the first mission - a manned or umanned preparatory construction mission - by 2040. Presumably mapper and prospector drones will precede them but those are too small, simple and expendable to be worried about.

BTW, my preferred way of communication is email but GitHub issues is fine too. I'm reachable at ak@triklod.rs

**Comment by vitiral** [comment]
Awesome to hear others have similar dreams! What you've described is basically a [level 5 Civboot](https://github.com/civboot/civboot/blob/main/thoughts/levels.md). Living on asteroids would likely require a near-infinite energy source (aka "cold" fusion or similar, you have to remember that bleeding heat is VERY expensive in space). However, if that were obtainable for a Civboot then I would think a Level 5 Civboot colony could live on asteroids.

Definitely in the "pipedream" category for me, but super fun to think about and be inspired from :smile: 

> So far, I'm trying to start a company for making robots that will both provide a breeding ground for further technologies, provide money for further steps on the ladder and perhaps be a point that people can come around.

I'm having similar thoughts for Civboot. My current thinking is a set of extremely robust, modular and infinitely hackable electronics solutions which could be used where connectivity is poor or cannot be guaranteed: remote folks, folks living on sailboats, oil rigs, military applications, space, etc.

The first products would essentially be highly reliable "toys" which are a STEM platform for building whatever you want. Maybe there would be a drone, a robot arm, and a small powered car. These could be used to build fun rube goldberg machines, or maybe your own at-home production facility for some small product. Eventually there would be more industrial-style solutions as well.

**Comment by vitiral** [comment]
Going to go ahead and close, thanks!
