### ISSUE TITLE
The Mote in God's Eye

### ISSUE THREAD

**Issue by SimonMeskens** [civboot/civboot#3]
Have you read The Mote in God's Eye? It's a classic sci-fi book that has civboots as one of the core plot points.

**Comment by vitiral** [comment]
I have never heard of it! I'll be on a 15 hour car ride soon so may just have to check it out, thanks

A few questions I have from reading the synopsis:

1. Do you recommend it as a good book?
2. It seems it's _mostly_ about alien first contact. Are Civboot-like technologies used as a major plot point or world building point?
3. Who has the Civboots, humans or the aliens?

Thanks!

**Comment by SimonMeskens** [comment]
1. It is my favorite science-fiction book, has a cult following and is generally considered to be a classic, so it's fairly safe for me to recommend it
2. It's mostly about alien first contact, but in a very novel way. The Civboot technologies form a major plot point for the climax of the story and are part of the world-building, so they are a major plot point, but not a major theme, if that makes sense. They are also not full Civboots in that each warehouse does not contain the means to produce itself, but rather, each warehouse is set up to teach a collapsed civilisation the technology needed to progress. The main reason I recommend it is because it takes a bit of a different approach to the idea of bootstrapping civilization.
3. The aliens are the ones who have the Civboot-like structures, but the book is part of a series of books that deals with civilizational collapse, so that is a theme for the humans as well. If you would happen to really like the book, the other book in the series that is worth checking out is King David's Spaceship, which deals more with collapsed civilizations.
