### ISSUE TITLE
Redefining what a Civboot is

### ISSUE THREAD

**Issue by SimonMeskens** [civboot/civboot#4]
I think it would be good to better define what a Civboot is, by better defining the parts.

1. Self-replicating structure: a warehouse able to create an identical copy of itself, using only the technology contained inside, a certain amount of labor and natural resources of the area it is in.
2. Technology-teaching bootstrap: a warehouse able to teach a certain technology (for example simple computers) to a person or group of people that does not possess that knowledge.
3. Ideas around technological "tiers", aka defining which technologies caused leaps in human technology throughout the ages. For example, a useful tier is precision engineering, which is often stated to be the result of lathes and mills (it's sometimes said that if you have a lathe and a mill, you can recreate modern society).

A Civboot is more of a holistic approach that combines all three of these ideas with a set of principles to make sure it is of the maximum use to society, but I think these three separate ideas are really interesting and important ideas in their own right, and should be discussed as such.

For example, when it comes to feasibility of the project, you could talk about a Civboot that aims at an earlier "technological tier" than simple computers, like maybe modern agriculture. Maybe there are people interesting in discussing a later tier, like space flight, and what that would entail.

Another interesting talking point is structures that do not contain one of these three elements. For example: a warehouse that is only aimed at teaching a group of people a certain foundational technology without supervision, but that does not have the means to build a copy of itself. This could be an interesting experiment too. Could we design a structure that you can just send laypeople into and have them emerge with tools and knowledge to perform a certain foundational task? Or maybe you could build a warehouse that is only self-replicating. Since every Civboot would need something like that, just talking about a warehouse that can be replicated is interesting in its own right. A last idea that is interesting is a warehouse that doesn't necessarily teach a foundational technology. For example, there could be a structure that only aims to teach a single person how to recreate the structure and learn the skills needed to build the structure. It wouldn't be a foundational technology, but it would teach us a lot about what each person is capable of on their own.

**Comment by vitiral** [comment]
Civboot levels was actually something I thought about from the very beginning. There is a somewhat [hidden link](https://github.com/civboot/civboot/blob/main/thoughts/levels.md) on the README. You can search for "levels", the link is in "here". It is extremely important to point out that the required complexity to make a "simple computer" is extremely high. Even 1980's era computers required multi-million dollar fabs. However, I think there is [some hope](https://www.nature.com/articles/s41598-019-53766-2) in low-temperature non-pure-silicone-substrate semiconductors. I'm talking to some of my old professors to get their take and want to do a podcast as soon as my life is a bit more stable.

Specifically, we have already achieved Civboot Level 0, which is to say the entire planet is Civboot level 0.

reduce/remove, simplify, modularize, repeat. I think everything you mentioned may be useful concepts/structures of how to _break down_ a Civboot into it's component pieces. Not only the technology, but the structure of the Civboot needs to follow this goal. After all, a Civboot has as a requirement to be able to teach ~500 high school through college students how to build a new Civboot with improvements!

However, it's all a bit too theoretical at the moment. Civboot is a concrete (but nearly impossible) goal. I'm really not certain about the best way to achieve it except there needs to be a massive narrowing of the gap in complexity of existing technology. For software, I'm working on it with https://github.com/vitiral/fngi. The software we can build will end up defining the hardware we need, so I consider it the first step.

We also need someone working on the mechanical/precision engineering and the chemical engineering components, which I consider largely distinct; although their automated tooling will be programmed by Civboot code using a Civboot OS and communication protocol. Hopefully somebody comes along with the passion to lead at least those two areas.

**Comment by SimonMeskens** [comment]
Unfortunately, though my areas of interest are all over the place, my only expertise areas are in software development and teaching sports. The former is already present and the latter is useless to this project. I'll keep my ears open though, in case I meet anyone interested in one of the engineering areas.

One of my interests is "experimental archaeology", which is basically understanding the past by recreating it to a degree and I think projects like these are invaluable tools to learn just how our modern society works. I consider projects like Civboot of the utmost importance in our understanding of technology.

**Comment by vitiral** [comment]
Sorry, I didn't mean to sound exclusive. I can use a TON of help on the software side of things too :D

**Comment by vitiral** [comment]
If you're feeling like pitching in, I'm working on firming up my "Spore Assembly" language at https://github.com/vitiral/fngi/blob/main/spore/asm2.sa and https://github.com/vitiral/fngi/blob/main/spore/testAsm2.sa. I would appreciate someone even looking at the syntax/etc. Incomplete docs are here: https://github.com/vitiral/fngi/blob/main/spore.md#spore-assembly

**Comment by vitiral** [comment]
I just updated the spore.md docs a bit in case you're already reading them.

**Comment by SimonMeskens** [comment]
I'm running a bunch of my own experiments in a similar space right now. Once I'm done with them, I'll have a look at what knowledge I can share and if I can contribute.

**Comment by vitiral** [comment]
closing for now.

Now is a good time to contribute to fngi if you are still interested. I am beginning to implement the "standard library" of the language.
